CREATE TABLE [dbo].[WeChatData]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Key] NVARCHAR(100) NOT NULL UNIQUE,
	[Value] NTEXT NOT NULL,
	[UpdateTime] DATETIME NOT NULL,
	CONSTRAINT UQ_WeChatData_Key UNIQUE ([Key])
)

